### ISSUE TITLE
WebDriver tests won't run in parallel

### ISSUE THREAD

**Issue by PatrickRice-KSC** [getgauge/gauge-gradle-plugin#42]
When creating Selenium-based tests within gauge, attempting to run them in parallel will cause Gauge to error with the following message:

>   05:31:22.573 [main] DEBUG org.reflections.Reflections - going to scan these urls:
// Jar and class file entries removed
Executing in 4 parallel streams.
org.reflections.ReflectionsException: could not create class object from file redacted
	at org.reflections.scanners.AbstractScanner.scan(AbstractScanner.java:32)
	at org.reflections.Reflections.scan(Reflections.java:253)
	at org.reflections.Reflections.scan(Reflections.java:202)
	at org.reflections.Reflections.<init>(Reflections.java:123)
	at com.thoughtworks.gauge.execution.parameters.parsers.base.ParameterParsingChain.createReflections(ParameterParsingChain.java:57)
	at com.thoughtworks.gauge.execution.parameters.parsers.base.ParameterParsingChain.<init>(ParameterParsingChain.java:43)
	at com.thoughtworks.gauge.connection.MessageDispatcher.initializeMessageProcessor(MessageDispatcher.java:109)
	at com.thoughtworks.gauge.connection.MessageDispatcher.<init>(MessageDispatcher.java:69)
	at com.thoughtworks.gauge.GaugeRuntime.dispatchMessages(GaugeRuntime.java:128)
	at com.thoughtworks.gauge.GaugeRuntime.lambda$connectInParallel$1(GaugeRuntime.java:101)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: Inflater has been closed
	at java.util.zip.Inflater.ensureOpen(Inflater.java:389)
	at java.util.zip.Inflater.inflate(Inflater.java:257)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:152)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.DataInputStream.readInt(DataInputStream.java:387)
	at javassist.bytecode.ClassFile.read(ClassFile.java:823)
	at javassist.bytecode.ClassFile.<init>(ClassFile.java:154)
	at org.reflections.adapters.JavassistAdapter.getOfCreateClassObject(JavassistAdapter.java:100)
	at org.reflections.adapters.JavassistAdapter.getOfCreateClassObject(JavassistAdapter.java:24)
	at org.reflections.scanners.AbstractScanner.scan(AbstractScanner.java:30)
	... 10 common frames omitted
Failed to initialize suite datastore. Error: Connection closed [127.0.0.1:34642] cause: read tcp 127.0.0.1:41363->127.0.0.1:34642: read: connection reset by peer
  Failed to initialize suite datastore. Error: Connection closed [127.0.0.1:34632] cause: read tcp 127.0.0.1:39503->127.0.0.1:34632: read: connection reset by peer
  Failed to initialize suite datastore. Error: Connection closed [127.0.0.1:53688] cause: read tcp 127.0.0.1:43117->127.0.0.1:53688: read: connection reset by peer
  Failed to initialize suite datastore. Error: Connection closed [127.0.0.1:57016] cause: read tcp 127.0.0.1:35161->127.0.0.1:57016: read: connection reset by peer

This error message will appear once per "node" allocated during the gradle command, and the ports are of course random each time. 

Configurations tested (All exhibit the same behavior):
Gradle 5.6.4 with Gauge Plugin 1.7.3 and 1.8.0 and Firefox WebDriver
Gradle 5.6.4 with Gauge Plugin 1.7.3 and 1.8.0 and Chrome WebDriver
Gradle 6.0.1 with Gauge Plugin 1.8.0 and Firefox WebDriver
Gradle 6.0.1 with Gauge Plugin 1.8.0 and Chrome WebDriver
Gradle 6.0.1 with Gauge Plugin 1.8.0 and Remote WebDriver

The expected behavior would be to spawn multiple browsers and run in parallel.

**Comment by PatrickRice-KSC** [comment]
This may have to do with the multi-threading setup within gauge, as setting "enable_multithreading = false" within properties allows the tests to execute as expected.

**Comment by NivedhaSenthil** [comment]
If possible can you please provide a sample where we can replicate this ?

**Comment by NivedhaSenthil** [comment]
Closing due to inactivity .. feel free to reopen if you are still facing the issue.
